### ISSUE TITLE
Use SQLite for introduction

### ISSUE THREAD

**Issue by etiennebr** [jonkeane/dittodb#100]
I don't want to nag you with this since I already mentioned it in my review :) but I thought maybe my suggestion wasn't clear. Feel free to close the issue.

I think that

https://github.com/jonkeane/dittodb/blob/14313369fa7214530e17df2e2c5f5470f159f9c6/vignettes/dittodb.Rmd#L31-L37

And

https://github.com/jonkeane/dittodb/blob/14313369fa7214530e17df2e2c5f5470f159f9c6/README.md#L51-L58

Could both use  `SQLite` to make the new users use `dittodb` much faster. Because even if it uses fixtures, the users still need to install two new packages to get to try the first two examples. Also `SQLite` has the advantage that it does not require to setup a backend to explore `dittodb` further.

**Comment by jonkeane** [comment]
Thank you for the reminder here. I thought I had addressed this in my responses, but I definitely had not. 

I definitely agree that (more) easily runable examples are good, the concern I had switching to all SQLite was that it defeats some of the motivation for `dittodb`. In most cases SQLite is useable without too much hassle on CI infrastructure (in fact, when I first was researching if there as prior art for `dittodb`, many people recommended that I use SQLite connections as my mocked DB connection). So I want to have something that shows the "hard" case of Postgres or MariaDB so it's obvious that's the solution that we're really aiming for.

That being said, I do agree with you that having SQLite examples for easy "run this quickly to see how it works" is nice. I've got a few ideas of ways I might be able to have both examples side by side. I'll let you know if/when I manage that, and we can see if that looks good?

**Comment by etiennebr** [comment]
Sounds good! Feel free to close or leave open if you want to track it.

**Comment by jonkeane** [comment]
It took a bit of work to get this integrated to the pkgdown building process (with a few minor hacks), but I've now added in backend-specific code chunks in tabs so that one can click through and see that it works the same regardless. I've included these both in the readme (which is then converted into the index page for dittodb.jonkeane.com as well as the dittodb vignette: https://dittodb.jonkeane.com/articles/dittodb.html#our-function-mean_delays

How does this look to you?

**Comment by pachamaltese** [comment]
hey.... this looks amazing!! with the tabs and all these changes it looks really great, it's almost weird that I feel like heppy just to look at the result

**Comment by jonkeane** [comment]
Thank you! It took a bit of fiddling and a bit of custom work to get it done, but it should be repeatable with any pkgdown site. The biggest change was adding code to my [`extra.js`](https://github.com/jonkeane/dittodb/blob/master/pkgdown/extra.js) that I _mostly_ copy/pasted from `rmarkdown` though had to edit slightly to accommodate the slight differences with html output from pkgdown+removing extraneous/empty TOC items.

For the readme.md, I also needed to slightly alter pkgdown (which hopefully will be merged in) https://github.com/r-lib/pkgdown/pull/1343
