### ISSUE TITLE
Expand a bit more about setup

### ISSUE THREAD

**Issue by jonkeane** [jonkeane/dittodb#102]
One should generally add `library(dittodb)` to `helpers.R` in the `testthat` directory. `httptest` has a helper function that does this automagically: https://github.com/nealrichardson/httptest/blob/master/R/use-httptest.R

Should we implement the `use_this` style or explain in docs?

**Comment by pachamaltese** [comment]
this is nice !! I'm starting to understand it

**Comment by jonkeane** [comment]
Resolved by #106
