### ISSUE TITLE
unable to find an inherited method for function 'dbExistsTable' for signature '"DBIMockConnection", "SQL"'

### ISSUE THREAD

**Issue by ndiquattro** [jonkeane/dittodb#112]
Hello again!

I have a test for code that uses `DBI::dbExistsTable()` to check if a table is around before creating/deleting it. It is throwing this error:

```
unable to find an inherited method for function 'dbExistsTable' for signature '"DBIMockConnection", "SQL"'
```

From what I can tell, it seems that it isn't being mocked by `dittodb`?

**Comment by jonkeane** [comment]
Hello again, and thanks for the awesome bug report. You're absolutely right that `dittodb` is missing a method for `dbExistsTable`. I must have missed it when I wrote #7 and thus haven't implemented it at all yet. 

It shouldn't be too difficult to implement (though I've been surprised by some of the small differences in driver's implementations of things that can get in the way) and I'll take a look into adding it shortly.

**Comment by jonkeane** [comment]
I just merged #113 into the main branch including methods for `dbExistsTable()`. Let me know if you have any issues with it

**Comment by ndiquattro** [comment]
Thanks for the fast follow-up! I'm getting the following error:

`Error in glue("dbExistsTable-{name}.R") : could not find function "glue"`

Looking at the code, seems like it needs to be `glue::glue`.

**Comment by pachamaltese** [comment]
@jonkeane let me send a PR

**Comment by jonkeane** [comment]
Sorry about that, we've added in `glue::`, would you mind trying to install the newest version and checking if that resolves this issue for you?

**Comment by ndiquattro** [comment]
works for me, thanks a lot!
