### ISSUE TITLE
glue:: error

### ISSUE THREAD

**Issue by pachamaltese** [jonkeane/dittodb#117]
Thanks for the fast follow-up! I'm getting the following error:

`Error in glue("dbExistsTable-{name}.R") : could not find function "glue"`

Looking at the code, seems like it needs to be `glue::glue`.

_Originally posted by @ndiquattro in https://github.com/jonkeane/dittodb/issues/112#issuecomment-644273955_

**Comment by jonkeane** [comment]
Thanks for this @pachamaltese !
