### ISSUE TITLE
Re-enable Postgres tests on Windows

### ISSUE THREAD

**Issue by jonkeane** [jonkeane/dittodb#120]
Something about the chocolatey install process for postgres changed 

This run was fine:
https://github.com/jonkeane/dittodb/runs/771329415?check_suite_focus=true

But after that, it looks like postgres is unreachable when the fixtures are loaded, even though it looks like it installed just fine (and uninstalling+reinstalling didn't resolve it)

For now we have disabled those postgres tests on windows, but we should re-enable them when postgres is installable again.

**Comment by pachamaltese** [comment]
this is strange, the same happens when testing on a VM
I'm not so brave to remove my postgres installation and test again

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk
