### ISSUE TITLE
Let me start/stop mocks with a function without needing to wrap all calls

### ISSUE THREAD

**Issue by jonkeane** [jonkeane/dittodb#47]
Make a `start_using_mocks` and `stop_using_mocks` or the like that lets me start an (interactive) session of using mocks so I can more easily iterate.

**Comment by pachamaltese** [comment]
sounds good!! how do we proceed?

**Comment by jonkeane** [comment]
Basically it's figuring out how to get https://github.com/jonkeane/dbtest/blob/master/R/mock-db.R#L38-L42 to run and stay present until you run something to stop it.

**Comment by jonkeane** [comment]
Closing in favor of #64
