### ISSUE TITLE
ropensci review todos

### ISSUE THREAD

**Issue by pachamaltese** [jonkeane/dittodb#76]
- [x] Community guidelines including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with URL, BugReports and Maintainer (which may be autogenerated via Authors@R).
- [ ] There is a code of conduct, but no contribution guidelines. There are some extra steps required to get databases set up for testing locally. You touched on it in the README, but I think you need more detailed instructions for how to get this set up, either as part of a CONTRIBUTING file, or as a README in the db-setup directory. 
- [ ] Use .Deprecated() for the functions which you have renamed (start_capturing, stop_capturing). That is the standard and it communicates to users that they are have moved.
- [x] Just wanted to point out if you didn't know: you can rename your "getting started" vignette to dittodb and it will show up in a "getting started" tab on your pkgdown site (https://pkgdown.r-lib.org/reference/build_articles.html#special-links).
- [ ] Good idea to include a vignette detailing the nycflights13 data. I think you should include a bit more info there: instructions for how to get it set up locally and a link to the nycflights13 package.
- [ ] Using grep in redact_columns() will potentially cause bugs (eg if someone has a df with two columns: column and other_column, then redact_columns("column") will result in an error because both will be matched.
- [ ] The README doesn't specify that the scripts are in the db-setup directory, so that took a minute to figure out
- [ ] I was already running a postgres server from my machine on port 5432, so I had to stop it to get the dockerized version to work for testing. I recommend using a port other than the default for the test db.

**Comment by pachamaltese** [comment]
@jonkeane with respect to this part from the review
> I was already running a postgres server from my machine on port 5432, so I had to stop it to get the dockerized version to work for testing. I recommend using a port other than the default for the test db.

I created the branch https://github.com/jonkeane/dittodb/tree/docker-changes that used other ports

**Comment by jonkeane** [comment]
I've got a lot of these tracked as separate issues: #63 #66 #69 #68 #65 #67 and #62 I think that basically covers those issues, but if any of them aren't overlapping feel free to open up a separate issue for each thing. 

I'm trying to make each fix on a branch and close the issue with the PR merge which is easier to do and coordinate with separate issues.
